# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 06:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([('followed_user', 'following_user')]),
        ),
    ]
